### ISSUE TITLE
Update Dockerfile distribution

### ISSUE THREAD

**Issue by jqueuniet** [jerakia/jerakia#147]
The official image on Dockerhub still uses Alpine 3.6 which will be EOL in May. The master Dockerfile has been updated to 3.7, which will be EOL in November.

Alpine 3.9 was published two months ago, will last until 2021-01-01 and could be a better base moving on.

**Comment by crayfishx** [comment]
Will get this tested and rolled up soon

**Comment by hhenkel** [comment]
@crayfishx This issue can propably be closed as the dockerfile was update with commit [17e786ee31d35deb297c1d8fc0ebcfac609c0b11](https://github.com/jerakia/jerakia/commit/17e786ee31d35deb297c1d8fc0ebcfac609c0b11)?

**Comment by NITEMAN** [comment]
Maybe related, [official docs](http://jerakia.io/basics/install/) points to a [non-working Docker image](https://hub.docker.com/r/crayfishx/jerakia)
